// partA.js: p2 partA: recreation of Nightingale plot
// Copyright (C)  2023 University of Chicago. All rights reserved.
/*
This is only for students and instructors in the 2023 CMSC 23900 ("DataVis") class, for use in that
class. It is not licensed for open-source or any other kind of re-distribution. Do not allow this
file to be copied or downloaded by anyone outside the 2023 DataVis class.
*/
'use strict';
import {
  captionText, capsMonth,
  // what do you want to import from common.js?
  // v.v.v.v.v.v.v.v.v.v.v.v.v.v.v  begin student code (partA imports)
  fnColor, dataProc, outColor,
  // ^'^'^'^'^'^'^'^'^'^'^'^'^'^'^  end student code (1L in ref)
  d3,
} from './common.js';

// new things you might want to use for partA()
// v.v.v.v.v.v.v.v.v.v.v.v.v.v.v  begin student code (partA new)
// ^'^'^'^'^'^'^'^'^'^'^'^'^'^'^  end student code (20L in ref)

// how you make part A
export const partA = (id, csvData) => {
  const svg = d3.select(`#${id}`);
  // v.v.v.v.v.v.v.v.v.v.v.v.v.v.v  begin student code (partA code)
  const data = dataProc(csvData);

  // creates padding
  svg.append("rect")
    .attr("x", 0)
    .attr("y", 0)
    .attr("width", 1100)
    .attr("height", 601)
    .attr("fill", fnColor.bkgd)

  //adds labeling
  svg.append("text")
    .attr("x", 851.8)
    .attr("y", 34)
    .attr("text-anchor", "middle")
    .attr("font-size", "14px")
    .text("1.")
  svg.append("text")
    .attr("x", 229.7)
    .attr("y", 34)
    .attr("text-anchor", "middle")
    .attr("font-size", "14px")
    .text("2.")
  svg.append("text")
    .attr("x", 851.8)
    .attr("y", 48)
    .attr("text-anchor", "middle")
    .attr("font-size", "14px")
    .text("APRIL 1854 to MARCH 1855")
  svg.append("text")
    .attr("x", 229.7)
    .attr("y", 48)
    .attr("text-anchor", "middle")
    .attr("font-size", "14px")
    .text("APRIL 1855 to MARCH 1856")
  svg.append("text")
    .attr("x", 550)
    .attr("y", 27)
    .attr("text-anchor", "middle")
    .attr("font-size", "20px")
    .text("DIAGRAM of the CAUSES of MORTALITY")
  svg.append("text")
    .attr("x", 550)
    .attr("y", 46)
    .attr("text-anchor", "middle")
    .attr("font-size", "18px")
    .text("in the ARMY in the EAST")
  svg.append("text")
    .attr("x", 85)
    .attr("y", 390.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[0][0])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 408.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[0][1])
  svg.append("text")
    .attr("x", 85)
    .attr("y", 425.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[1][0])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 443.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[1][1])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 460.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[1][2])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 478.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[1][3])
  svg.append("text")
    .attr("x", 85)
    .attr("y", 495.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[2][0])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 513.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[2][1])
  svg.append("text")
    .attr("x", 85)
    .attr("y", 530.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[3][0])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 548.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[3][1])
  svg.append("text")
    .attr("x", 85)
    .attr("y", 565.65)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[4][0])
  svg.append("text")
    .attr("x", 104)
    .attr("y", 583.15)
    .attr("text-anchor", "start")
    .attr("font-size", "14px")
    .text(captionText[4][1])

  // sliced the data into halves in order to use for the radius
  const middle = Math.ceil(data.length / 2);
  const firstHalf = data.splice(0, middle);
  const secondHalf = data.splice(-middle);

  // makes arcs: starts at 270 degrees and rotate by 30 degrees for each arc
  // used A = PI*r^2/12, where the area of sector is the death rate
  const arcgen0 = (d, i, r) =>
    d3.arc()
      .innerRadius(0)
      .outerRadius(Math.sqrt(r * 12 / Math.PI)*5.1)
      .startAngle(3*Math.PI / 2 + 1/6*Math.PI*i)
      .endAngle(3*Math.PI / 2 + 1/6*Math.PI*i + 1/6*Math.PI)();

  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.zWej')
    .attr('d', (d, i) => arcgen0(d, i, d.zRate))
    .attr('fill', fnColor.blue)
    .attr('stroke-width', 0)
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.oWej')
    .attr('d', (d, i) => arcgen0(d, i, d.oRate))
    .attr('fill', fnColor.gray)
    .attr('stroke-width', 0)
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.wWej')
    .attr('d', (d, i) => arcgen0(d, i, d.wRate))
    .attr('fill', fnColor.pink)
    .attr('stroke-width', 0)
  //appends the text to the wedges
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('text')
    .attr('class', '.zWej-text')
    .attr('x', (d, i) => {
      const r = Math.sqrt(d.zRate * 12 / Math.PI)*5.1;
      const angle = 3*Math.PI / 2 + 1/6*Math.PI*i + 1/12*Math.PI;
      return (r+35) * Math.cos(angle+(3*Math.PI/2));
    })
    .attr('y', (d, i) => {
      const r = Math.sqrt(d.zRate * 12 / Math.PI)*5.1;
      const angle = 3*Math.PI / 2 + 1/6*Math.PI*i + 1/12*Math.PI;
      return (r+35) * Math.sin(angle+(3*Math.PI/2));
    })
    .attr('text-anchor', 'middle')
    .attr('font-size', '12px')
    .attr('fill', 'black')
    .text(d => d.month)

 
  // this makes the outlines for the wedges
  // fill with none to make the wedges below visible
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.zWej-outlines')
    .attr('d', (d, i) => arcgen0(d, i, d.zRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.blue)
    .attr('stroke-width', 1.2)
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.oWej-outlines')
    .attr('d', (d, i) => arcgen0(d, i, d.oRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.gray)
    .attr('stroke-width', 1.2)
  svg.append('g')
    .attr('transform', 'translate(811.8, 234.39)')
    .selectAll('wedges')
    .data(firstHalf)
    .join('path')
    .attr('class', '.wWej')
    .attr('d', (d, i) => arcgen0(d, i, d.wRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.pink)
    .attr('stroke-width', 1.2)

  // here begins the next graph (the one on the left)
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.zWej')
    .attr('d', (d, i) => arcgen0(d, i, d.zRate))
    .attr('fill', fnColor.blue)
    .attr('stroke-width', 0)
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.wWej')
    .attr('d', (d, i) => arcgen0(d, i, d.wRate))
    .attr('fill', fnColor.pink)
    .attr('stroke-width', 0)
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.oWej')
    .attr('d', (d, i) => arcgen0(d, i, d.oRate))
    .attr('fill', fnColor.gray)
    .attr('stroke-width', 0)
 
  // makes outlines for wedges
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.zWej-outlines')
    .attr('d', (d, i) => arcgen0(d, i, d.zRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.blue)
    .attr('stroke-width', 1.2)
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.wWej')
    .attr('d', (d, i) => arcgen0(d, i, d.wRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.pink)
    .attr('stroke-width', 1.2)
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('path')
    .attr('class', '.oWej-outlines')
    .attr('d', (d, i) => arcgen0(d, i, d.oRate))
    .attr('fill', 'none')
    .attr('stroke', outColor.gray)
    .attr('stroke-width', 1.2)
  //appends the text to the wedges
  svg.append('g')
    .attr('transform', 'translate(249.7, 234.39)')
    .selectAll('wedges')
    .data(secondHalf)
    .join('text')
    .attr('class', '.zWej')
    .attr('x', (d, i) => {
      const r = Math.sqrt(d.zRate * 12 / Math.PI)*5.1;
      const angle = 3*Math.PI / 2 + 1/6*Math.PI*i + 1/12*Math.PI;
      return (r+25) * Math.cos(angle+(3*Math.PI/2));
    })
    .attr('y', (d, i) => {
      const r = Math.sqrt(d.zRate * 12 / Math.PI)*5.1;
      const angle = 3*Math.PI / 2 + 1/6*Math.PI*i + 1/12*Math.PI;
      return (r+25) * Math.sin(angle+(3*Math.PI/2));
    })
    .text(d => d.month)
    .attr('font-size', "9.5px")
    .attr('text-anchor', 'middle')
  // ^'^'^'^'^'^'^'^'^'^'^'^'^'^'^  end student code (136L in ref)
};
